---
title: "Analysis"
author: "Shan He"
date: "4/27/2020"
output: html_document
---

Run the model including only time-independent variables first. Stratifying by county and not stratifying by county.
```{r}
# not stratifed by county
simple_log = lm(log(daily_r)~log(winter_tmmx)+log(winter_rmax)+log(susceptible_perc)
                +log(density)+log(withHS)+log(Poverty_percentage)
                +log(AfriAm_perc)+log(older_perc),data=cases_and_fixed)
summary(simple_log)

# stratifed by county
simple_log_strat = lm(log(daily_r)~log(winter_tmmx)+log(winter_rmax)+log(susceptible_perc)
                +log(density)+log(withHS)+log(Poverty_percentage)
                +log(AfriAm_perc)+log(older_perc)+Countynames,data=cases_and_fixed)
summary(simple_log_strat)

```

Fixed variables and one time-varying covariate (testing)
```{r}
# go back 5 days
test_log5 = lm(log(daily_r)~log(winter_tmmx)+log(winter_rmax)+log(susceptible_perc)
                +log(density)+log(withHS)+log(Poverty_percentage)
                +log(AfriAm_perc)+log(older_perc)+log(relative_test)+
              log(days_ago4)+log(days_ago3)+log(days_ago2)+log(days_ago1),data=cases_fixed_test)
summary(test_log5)

# go back 10 days
test_log10 = lm(log(daily_r)~log(winter_tmmx)+log(winter_rmax)+log(susceptible_perc)
                +log(density)+log(withHS)+log(Poverty_percentage)
                +log(AfriAm_perc)+log(older_perc)+log(relative_test)+
              log(days_ago9)+log(days_ago8)+log(days_ago7)+log(days_ago6)+log(days_ago5)+
              log(days_ago4)+log(days_ago3)+log(days_ago2)+log(days_ago1),data=cases_fixed_test)
summary(test_log10)
```

Fixed and three time-varying covariates
```{r}
# go back 5 days
fixed_3policy_lm_5days = lm(log(daily_r)~log(winter_tmmx)+log(winter_rmax)+log(susceptible_perc)+log(density)+log(withHS)+log(Poverty_percentage)+log(AfriAm_perc)+log(older_perc)+log(relative_test)+log(days_ago4)+log(days_ago3)+log(days_ago2)+log(days_ago1)+Social_Distancing+SD_days_ago4+SD_days_ago3+SD_days_ago2+SD_days_ago1+Mask+M_days_ago4+M_days_ago3+M_days_ago2+M_days_ago1,data=cases_fixed_test_SD_Mask)

summary(fixed_3policy_lm_5days)

# go back 10 days
fixed_3policy_lm_10days = lm(log(daily_r)~log(winter_tmmx)+log(winter_rmax)+log(susceptible_perc)+log(density)+log(withHS)
                             +log(Poverty_percentage)+log(AfriAm_perc)+log(older_perc)+log(relative_test)+log(days_ago9)+log(days_ago8)
                             +log(days_ago7)+log(days_ago6)+log(days_ago5)+log(days_ago4)+log(days_ago3)+log(days_ago2)+log(days_ago1)
                             +Social_Distancing+SD_days_ago9+SD_days_ago8+SD_days_ago7+SD_days_ago6+SD_days_ago5+SD_days_ago4+SD_days_ago3
                             +SD_days_ago2+SD_days_ago1+Mask+M_days_ago9+M_days_ago8+M_days_ago7+M_days_ago6+M_days_ago5+M_days_ago4+M_days_ago3
                             +M_days_ago2+M_days_ago1,data=cases_fixed_test_SD_Mask)
summary(fixed_3policy_lm_10days)
```




